export  const SET_SINGER="SET_SINGER"

export const SET_PLAYING_STATE="SET_PLAYING_STATE"

export const SET_FULLSCREEN_STATE="SET_FULLSCREEN_STATE"

export const SET_PLAYLIST_STATE="SET_PLAYLIST_STATE"

export const SET_SEQUENCELIST_STATE="SET_SEQUENCELIST_STATE"

export const SET_MODE_STATE="SET_MODE_STATE"

export const SET_CURRENTINDEX_STATE="SET_CURRENTINDEX_STATE"
export const SET_DISC="SET_DISC"

export const SET_TOPLIST="SET_TOPLIST"
export const SET_HISTORY="SET_HISTORY"
export const SET_PLAYHISTORY="SET_PLAYHISTORY"
export const SET_FAVORITE_LIST="SET_FAVORITE_LIST"